package com.cs31620.quizel.ui.components

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data class to hold the score objects in the quiz
 * These objects are stored in the scores table in the db
 * @param id the id of the score, autogenerated
 * @param username the username of the user who scored, defaulted to user
 * @param score the user's score, defaulted to 0
 * @param numQuestions the number of questions in the quiz, used to show the correct with respect to the total , defaulted to 0
 */
@Entity(tableName = "scores")
data class Score(
    @PrimaryKey(autoGenerate = true)
    var id: Int = 0,
    var username: String = "User", //defaults, although this is only in error handling, since this should never normally happen
    var score: Int = 0,
    var numQuestions: Int = 0,
)